datasource1:
   jdbc:
      url: jdbc:postgresql://localhost:5432/testdb
      driverclass: org.postgresql.Driver
      username: admin
      password: password
   hibernate:
      hbm2ddl: update
      showsql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect
      
      