#database configurations
hibernate:
   connection:
      driver_class: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mydatabase
      username: root
      password: password
   hbm2ddl:
      auto: validate
   dialect: org.hibernate.dialect.MySQLDialect
show_sql: true