uri:
   login: /api/userService/users/login
   
server:
  port: 8083
  

zuul:
  prefix: /api
  routes:
    userService:
       path: /userService/**
       url: http://localhost:8086/
    productService:
       path: /productService/**
       url: http://localhost:8085