#database configurations
hibernate:
   connection:
      driver_class: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mydatabase
      username: root
      #password: password
      password: ENC(ainZYGWSiLRVpxaOXKp1Txpb0ULczTYq)
   hbm2ddl:
      auto: validate
   dialect: org.hibernate.dialect.MySQLDialect
show_sql: true

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    #ideally the below key should be parameterized
    password: secretkey



